### ISSUE TITLE
Erreur 500 : page vide sur saisie d'URL racine du site

### ISSUE THREAD

**Issue by bugeaud** [MedShake/MedShakeEHR-base#141]
De façon aléatoire, une erreur 500 est générée suite à la saisie de l'URL dans la barre d'adresse.

L'erreur suivante apparait ensuite :

`[Mon Jan 16 19:02:49.759043 2023] [php:error] [pid 28] [client host:50825] PHP Fatal error:  Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /app/MedShakeEHR-base/class/msTools.php:58\nStack trace:\n#0 /app/MedShakeEHR-base/controlers/login/logOutDo.php(30): msTools::redirRoute()\n#1 /app/MedShakeEHR-base/class/msUser.php(154): include('...')\n#2 /app/MedShakeEHR-base/class/msUser.php(110): msUser::cleanBadAuth()\n#3 /app/MedShakeEHR-base/public_html/index.php(99): msUser->userIdentification()\n#4 {main}\n  thrown in /app/MedShakeEHR-base/class/msTools.php on line 58`

J'ai pour l'instant du mal à reproduire l'erreur systématiquement mais elle a bien lieu régulièrement. De ce fait, il se peut qu'elle soit due à un timeout (cookie ?). La question du lien avec #135 se pose également.

**Comment by MedShake** [comment]
J'ai une idée. 
Quand on n'est pas logué  / renvoie sur /login/
Quand on est logué / renvoie  sur /patients/
Doit pas y'avoir d'erreur 500 dans le tas, aucune raison.

Par contre j'ai le souvenir d'avoir eu des erreurs 500 dans un tout autre cadre, celui  d'un appel en http et pas https sur un site configuré en théorie pour du https. Y'avait le bidouille dans les vhosts et compagnie et la redirection ne fonctionnait pas. Je parle bien ici d'un truc totalement hors cet EHR.  Bref, à vérifier si l'ehr est bien en cause ou pas.

**Comment by bugeaud** [comment]
J'ai eut ce problème sur un environement de test isolé en HTTP seul sans aucun autre utilisateur que celui ayant eut le problème. Le problème est donc propre à cet appel. Je vais essayer de trouver un scénario qui le reproduise et récuperer un pcap et plus de trace si possible.

**Comment by bugeaud** [comment]
Slash ou pas, tien de plus.

Voici l'access log du problème 
`"host:80 ip-address - - [16/Jan/2023:19:02:49 +0100] "GET / HTTP/1.1" 500 932 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"`

Il y avait bien un / ... je vais continuer d'essayer dans les prochains jours en laissant mon enregistreur de réseau tourner.
