### ISSUE TITLE
Echec lors des accès aux médicaments

### ISSUE THREAD

**Issue by htristra** [MedShake/MedShakeEHR-base#40]
Bonjour, 
je commencerais par les traditionnelles félicitations pour votre travail. Votre application est top pour le suivi. Je suis en train de déployer en test pour mon épouse et vais pousser pour qu'elle soit adoptée ;)
Je fais tourner sur une debian 9.5/apache2/php7.0.30
Les modules installés sont :
- base v4.1.0
- medge v1.0.0

Je n'ai pas rencontré de problèmes particuliers pendant l'installation du module de base.
Pour info, j'ai dû rejouer le script **sqlUpgrade_v4.0.0_v4.1.0.sql** pendant l'installation du module de médecine générale. Les champs tarifUnit, C,D,E, ..., n'étaient pas présent dans la table actes_base.

Une fois ceci fait, tout est ok ou presque.
J'ai des erreurs lors de l'utilisation des médicaments.
Si je vais sur l'url outils/lap/, j'ai une page blanche et l'erreur php suivante : 
`[Sun Sep 09 02:36:54.871585 2018] [:error] [pid 16792] [client 192.168.2.29:50199] PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in /opt/MedShakeEHR/class/msLap.php:66\nStack trace:\n#0 /opt/MedShakeEHR/controlers/lap/lapOutilsIndex.php(33): msLap->__construct()\n#1 /var/www/html/patients/index.php(111): include('/opt/MedShakeEH...')\n#2 {main}\n  thrown in /opt/MedShakeEHR/class/msLap.php on line 66, referer: http://192.168.2.39/patients/configuration/modules/`

Si je fais une nouvelle ordonnance médicamenteuse, j'ai la popin **"Problème, rechargez la page !"** et l'erreur php suivante : 
`[Sun Sep 09 02:40:29.620537 2018] [:error] [pid 16792] [client 192.168.2.29:50455] PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in /opt/MedShakeEHR/class/msLap.php:66\nStack trace:\n#0 /opt/MedShakeEHR/controlers/lap/actions/inc-ajax-lapTTenCoursGet.php(30): msLap->__construct()\n#1 /opt/MedShakeEHR/controlers/lap/actions/lapAjax.php(78): include('/opt/MedShakeEH...')\n#2 /var/www/html/patients/index.php(111): include('/opt/MedShakeEH...')\n#3 {main}\n  thrown in /opt/MedShakeEHR/class/msLap.php on line 66, referer: http://192.168.2.39/patients/patient/5/`

Si je fais une nouvelle prescription, j'ai la même popin et le message l'erreur suivante : 
`[Sun Sep 09 02:42:06.447483 2018] [:error] [pid 16802] [client 192.168.2.29:50569] PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in /opt/MedShakeEHR/class/msLap.php:66\nStack trace:\n#0 /opt/MedShakeEHR/controlers/lap/actions/inc-ajax-searchNewMedic.php(32): msLap->__construct()\n#1 /opt/MedShakeEHR/controlers/lap/actions/lapAjax.php(78): include('/opt/MedShakeEH...')\n#2 /var/www/html/patients/index.php(111): include('/opt/MedShakeEH...')\n#3 {main}\n  thrown in /opt/MedShakeEHR/class/msLap.php on line 66, referer: http://192.168.2.39/patients/patient/5/`

J’espère que ce n'est pas trop grave docteur .... 
A+

**Comment by MedShake** [comment]
Bonjour 

Merci pour vos retours. Je suis content de voir que cette version medgé intéresse ! 
Il faut que je me remette dans le bain, car je n'ai pas vraiment touché à l'EHR depuis début août. 
Il faut savoir que cette version medgé est vraiment neuve, brute de décoffrage pour le moment et peu testée. 

Pour les pb de bdd, je vais regarder tout ça et ajuster, à moins que vous n'ayez un pull request au chaud !

Pour la base médicamenteuse, la question évidente est : avez-vous accès au webservice Thériaque ou la base au format postgre ? Car sans accès / base, pas de LAP et pas d'ordo médicamenteuse.
Ensuite, avez-vous consulté cet article : http://www.logiciel-cabinet-medical.fr/documentation-technique/lap-mise-en-production.html ?
Les messages d'erreur doivent être majoritairement liés au fait que theriaqueMode soit vide. 

Bref, dites-moi ... !

B.
